### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [eybmv/franklin-w-dixon_the-secret-of-the-old-mill#1]
# General issues:

- [x] Re-run `se modernize-spelling .` and commit the change.

- [x] We don't change `near by` to `nearby` as this is just British spelling. It's very common to see a mixture of British and American spelling in books. You will need to do an interactive rebase to remove the commit. If you need help, feel free to ask!

# chapter-15.xhtml:

- [x] There is a lint error for `<i epub:type="se:name.vessel.boat">Sleuth’s</i>`. Move `’s` outside the italics.

# content.opf:

- [x] The short description should be a single complete sentence ([SEMOS 9.6.1.1](https://standardebooks.org/manual/1.7.4/9-metadata#9.6.1.1)).

**Comment by eybmv** [comment]
For replacing near by, I cannot just squash the two words back together on every instance? I think I dedicated just one commit to it, so it's not tangled up with anything else.

**Comment by EmmaSweeney** [comment]
We don't change British spelling to American spelling or vice versa. This would take you down a very deep rabbit hole, one you wouldn't want to go down.

It looks like you also need to add [Editorial] to the new `se modernize-spelling` commit.

**Comment by eybmv** [comment]
Gotcha; that does sound like a nightmare... but, I suppose my actual question is more, why rebase when I could just make a different commit separating the words from joined?

Otherwise, all fixed up!

**Comment by EmmaSweeney** [comment]
It's best practice to remove commits rather than create another [Editorial] commit. It can be hard to keep track of changes that are reverted if there are hundreds of other [Editorial] commits in a production.
